version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: ..
    dockerfile: airflow/Dockerfile
  environment:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  volumes:
    - ../src:/app/src
    - ./dags:/opt/airflow/dags
    - airflow_db:/opt/airflow

services:
  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        airflow db migrate &&
        echo 'DB migration complete.'
      "
    restart: "no"

  airflow:
    <<: *airflow-common
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: airflow standalone
    ports:
      - "8080:8080"

volumes:
  airflow_db:
